### ISSUE TITLE
Fix demo page

### ISSUE THREAD

**Issue by elwayman02** [elwayman02/ember-cli-password-strength#66]
ember-cli-github-pages seems to throw an error when trying to generate the demo app in Ember 2.16, not sure why.

**Comment by elwayman02** [comment]
```
> ember github-pages:commit --message "Deploy gh-pages from commit $(git rev-parse HEAD)"; git push; git checkout -

stdout maxBuffer exceeded
Error: stdout maxBuffer exceeded
    at Socket.onChildStdout (child_process.js:325:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:595:20)
```

**Comment by elwayman02** [comment]
For now I'll roll back the demo to the previous version.
